#%RAML 1.0
title: User API
version: v1
mediaType: application/json
baseUri: hb://user

/users:
  get:
    responses:
      200:
  post:
    responses:
      201:

/users/{user_id}:
  uriParameters:
    user_id: string
  get:
  patch:
    responses:
      204:
