#%RAML 1.0
title: User API
version: v1
mediaType: application/json
baseUri: hb://user

types:
  UpdatedUser:
    type: object
    properties:
      user_id: string

/users:
  get:
    queryParameters:
      fields?: string[]
    responses:
      200:
  post:
    responses:
      201:
        body: UpdatedUser
      200:
        body: UpdatedUser

/users/{user_id}:
  uriParameters:
    user_id: string
  get:
  patch:
    responses:
      200:
        body: UpdatedUser
